import { css } from 'remix/ui'

/** Shared, semantic design tokens. Components should choose roles, not own colors. */
export const tokens = {
  palette: {
    primary: { main: '#24785a', dark: '#19583f', light: '#e8f3ec', contrastText: '#ffffff' },
    success: { main: '#24785a', dark: '#19583f', light: '#e8f3ec' },
    warning: { main: '#b87328', dark: '#8f551b', light: '#fbf0df' },
    info: { main: '#4c7187', dark: '#36586d', light: '#eaf1f5' },
    error: { main: '#a64d46', dark: '#843a34', light: '#f8eae8' },
    text: { primary: '#18231f', secondary: '#52615a', muted: '#78847d' },
    background: { default: '#f5f7f4', paper: '#ffffff', subtle: '#f7f9f7', hover: '#eef2ee' },
    divider: '#e5e9e5',
    dividerStrong: '#cbd4cd',
    focus: '#9ac7ad',
  },
  spacing: { 0: '0px', 1: '4px', 2: '8px', 3: '12px', 4: '16px', 5: '24px', 6: '32px', 8: '48px' },
  shape: { small: '9px', medium: '12px', large: '14px', pill: '999px' },
  typography: {
    fontFamily:
      "Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
    size: {
      caption: '11px',
      small: '13px',
      body: '14px',
      section: '17px',
      metric: '29px',
      metricSmall: '23px',
      timer: '36px',
    },
    weight: { regular: 400, medium: 550, semibold: 600, bold: 700 },
  },
  elevation: { low: '0 2px 7px rgb(24 35 31 / 3%)' },
} as const

export type ThemeTokens = typeof tokens

/** Typed references for component styles; invalid token paths fail at compile time. */
export const themeTokens = {
  palette: {
    primary: {
      main: 'var(--palette-primary-main)',
      dark: 'var(--palette-primary-dark)',
      light: 'var(--palette-primary-light)',
      contrastText: 'var(--palette-primary-contrast-text)',
    },
    success: {
      main: 'var(--palette-success-main)',
      dark: 'var(--palette-success-dark)',
      light: 'var(--palette-success-light)',
    },
    warning: {
      main: 'var(--palette-warning-main)',
      dark: 'var(--palette-warning-dark)',
      light: 'var(--palette-warning-light)',
    },
    info: {
      main: 'var(--palette-info-main)',
      dark: 'var(--palette-info-dark)',
      light: 'var(--palette-info-light)',
    },
    error: {
      main: 'var(--palette-error-main)',
      dark: 'var(--palette-error-dark)',
      light: 'var(--palette-error-light)',
    },
    text: {
      primary: 'var(--palette-text-primary)',
      secondary: 'var(--palette-text-secondary)',
      muted: 'var(--palette-text-muted)',
    },
    background: {
      default: 'var(--palette-background-default)',
      paper: 'var(--palette-background-paper)',
      subtle: 'var(--palette-background-subtle)',
      hover: 'var(--palette-background-hover)',
    },
    divider: 'var(--palette-divider)',
    dividerStrong: 'var(--palette-divider-strong)',
    focus: 'var(--palette-focus)',
  },
  spacing: {
    0: '0px',
    1: 'var(--spacing-1)',
    2: 'var(--spacing-2)',
    3: 'var(--spacing-3)',
    4: 'var(--spacing-4)',
    5: 'var(--spacing-5)',
    6: 'var(--spacing-6)',
    8: 'var(--spacing-8)',
  },
  shape: {
    small: 'var(--shape-small)',
    medium: 'var(--shape-medium)',
    large: 'var(--shape-large)',
    pill: 'var(--shape-pill)',
  },
  typography: {
    size: {
      caption: 'var(--typography-size-caption)',
      small: 'var(--typography-size-small)',
      body: 'var(--typography-size-body)',
      section: 'var(--typography-size-section)',
      metric: 'var(--typography-size-metric)',
      metricSmall: 'var(--typography-size-metric-small)',
      timer: 'var(--typography-size-timer)',
    },
    weight: {
      medium: 'var(--typography-weight-medium)',
      semibold: 'var(--typography-weight-semibold)',
      bold: 'var(--typography-weight-bold)',
    },
  },
  elevation: { low: 'var(--elevation-low)' },
} as const

export const theme = css({
  '--palette-primary-main': tokens.palette.primary.main,
  '--palette-primary-dark': tokens.palette.primary.dark,
  '--palette-primary-light': tokens.palette.primary.light,
  '--palette-primary-contrast-text': tokens.palette.primary.contrastText,
  '--palette-success-main': tokens.palette.success.main,
  '--palette-success-dark': tokens.palette.success.dark,
  '--palette-success-light': tokens.palette.success.light,
  '--palette-warning-main': tokens.palette.warning.main,
  '--palette-warning-dark': tokens.palette.warning.dark,
  '--palette-warning-light': tokens.palette.warning.light,
  '--palette-info-main': tokens.palette.info.main,
  '--palette-info-dark': tokens.palette.info.dark,
  '--palette-info-light': tokens.palette.info.light,
  '--palette-error-main': tokens.palette.error.main,
  '--palette-error-dark': tokens.palette.error.dark,
  '--palette-error-light': tokens.palette.error.light,
  '--palette-text-primary': tokens.palette.text.primary,
  '--palette-text-secondary': tokens.palette.text.secondary,
  '--palette-text-muted': tokens.palette.text.muted,
  '--palette-background-default': tokens.palette.background.default,
  '--palette-background-paper': tokens.palette.background.paper,
  '--palette-background-subtle': tokens.palette.background.subtle,
  '--palette-background-hover': tokens.palette.background.hover,
  '--palette-divider': tokens.palette.divider,
  '--palette-divider-strong': tokens.palette.dividerStrong,
  '--palette-focus': tokens.palette.focus,
  '--spacing-1': tokens.spacing[1],
  '--spacing-2': tokens.spacing[2],
  '--spacing-3': tokens.spacing[3],
  '--spacing-4': tokens.spacing[4],
  '--spacing-5': tokens.spacing[5],
  '--spacing-6': tokens.spacing[6],
  '--spacing-8': tokens.spacing[8],
  '--shape-small': tokens.shape.small,
  '--shape-medium': tokens.shape.medium,
  '--shape-large': tokens.shape.large,
  '--shape-pill': tokens.shape.pill,
  '--typography-font-family': tokens.typography.fontFamily,
  '--typography-size-caption': tokens.typography.size.caption,
  '--typography-size-small': tokens.typography.size.small,
  '--typography-size-body': tokens.typography.size.body,
  '--typography-size-section': tokens.typography.size.section,
  '--typography-size-metric': tokens.typography.size.metric,
  '--typography-size-metric-small': tokens.typography.size.metricSmall,
  '--typography-size-timer': tokens.typography.size.timer,
  '--typography-weight-medium': tokens.typography.weight.medium,
  '--typography-weight-semibold': tokens.typography.weight.semibold,
  '--typography-weight-bold': tokens.typography.weight.bold,
  '--elevation-low': tokens.elevation.low,
  '& *, & *::before, & *::after': { boxSizing: 'border-box' },
  margin: 0,
  minHeight: '100vh',
  background: 'var(--palette-background-default)',
  color: 'var(--palette-text-primary)',
  fontFamily: 'var(--typography-font-family)',
  fontSize: 'var(--typography-size-body)',
  lineHeight: 1.5,
  WebkitFontSmoothing: 'antialiased',
  '& button, & input': { font: 'inherit' },
  '& button:focus-visible, & a:focus-visible, & input:focus-visible': {
    outline: '3px solid var(--palette-focus)',
    outlineOffset: '2px',
  },
})

export const panelStyle = css({
  background: 'var(--palette-background-paper)',
  border: '1px solid var(--palette-divider)',
  borderRadius: 'var(--shape-large)',
  boxShadow: 'var(--elevation-low)',
})

export const quietButtonStyle = css({
  appearance: 'none',
  display: 'inline-flex',
  alignItems: 'center',
  justifyContent: 'center',
  gap: 'var(--spacing-2)',
  minHeight: '38px',
  padding: 'var(--spacing-2) var(--spacing-3)',
  border: '1px solid var(--palette-divider)',
  borderRadius: 'var(--shape-small)',
  background: 'var(--palette-background-paper)',
  color: 'var(--palette-text-primary)',
  fontWeight: tokens.typography.weight.semibold,
  textDecoration: 'none',
  cursor: 'pointer',
  transition: 'background 140ms ease, border-color 140ms ease',
  '&:hover': {
    background: 'var(--palette-background-subtle)',
    borderColor: 'var(--palette-divider-strong)',
  },
})

export const primaryButtonStyle = css({
  appearance: 'none',
  display: 'inline-flex',
  alignItems: 'center',
  justifyContent: 'center',
  gap: 'var(--spacing-2)',
  minHeight: '40px',
  padding: '9px 14px',
  border: '1px solid var(--palette-primary-main)',
  borderRadius: 'var(--shape-small)',
  background: 'var(--palette-primary-main)',
  color: 'var(--palette-primary-contrast-text)',
  fontWeight: tokens.typography.weight.semibold,
  textDecoration: 'none',
  cursor: 'pointer',
  transition: 'background 140ms ease, border-color 140ms ease, transform 140ms ease',
  '&:hover': {
    background: 'var(--palette-primary-dark)',
    borderColor: 'var(--palette-primary-dark)',
  },
  '&:active': { transform: 'translateY(1px)' },
})

export const eyebrowStyle = css({
  margin: 0,
  color: 'var(--palette-text-muted)',
  fontSize: 'var(--typography-size-caption)',
  fontWeight: tokens.typography.weight.bold,
  letterSpacing: '0.09em',
  lineHeight: 1.3,
  textTransform: 'uppercase',
})
